version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - fl-net

  client1:
    build: ./client
    depends_on:
      - server
    networks:
      - fl-net

  client2:
    build: ./client
    depends_on:
      - server
    networks:
      - fl-net

networks:
  fl-net:
    driver: bridge